
---

- name: Configure S3 Storage
  block:
    - name: Validate Metering S3 bucket name
      assert:
        that:
          - meteringconfig_storage_s3_bucket_name != ""
          - meteringconfig_storage_s3_bucket_region != ""
        msg: "storage.hive.s3.bucket and storage.hive.s3.region cannot be empty"

    - name: Validate Metering S3 credentials
      assert:
        that:
          - meteringconfig_storage_s3_aws_credentials_secret_name != ""
        msg: "storage.hive.s3.secretName cannot be empty"

    - name: Obtaining AWS credentials to configure S3 bucket
      k8s_facts:
        api_version: v1
        kind: Secret
        name: "{{ meteringconfig_storage_s3_aws_credentials_secret_name }}"
        namespace: "{{ meta.namespace }}"
      no_log: true
      register: operator_s3_credentials_secret

    - name: Create Metering S3 bucket
      s3_bucket:
        state: present
        name: "{{ meteringconfig_storage_s3_bucket_name }}"
        region: "{{ meteringconfig_storage_s3_bucket_region }}"
        aws_access_key: "{{ operator_s3_credentials_secret.resources[0].data['aws-access-key-id'] | b64decode | default(omit) }}"
        aws_secret_key: "{{ operator_s3_credentials_secret.resources[0].data['aws-secret-access-key'] | b64decode | default(omit) }}"
      when: operator_s3_credentials_secret.resources | length > 0

  when: meteringconfig_storage_hive_storage_type == 's3' and meteringconfig_storage_s3_create_bucket

- name: Get azure storage account name
  block:
    - name: Get Azure storage credentials secret
      k8s_facts:
        api_version: v1
        kind: Secret
        name: "{{ meteringconfig_spec.storage.hive.azure.secretName }}"
        namespace: "{{ meta.namespace }}"
      register: azure_secret_buf

    - name: Verify azure storage credentials secret exists
      assert:
        that:
          - azure_secret_buf is defined and azure_secret_buf.resources | length > 0
          - azure_secret_buf.resources[0].data['azure-storage-account-name'] != ""
    - name: Extract Azure storage account name
      set_fact:
        _azure_secret_account_name: "{{ azure_secret_buf.resources[0].data['azure-storage-account-name'] | b64decode | default(omit)  }}"
  when: meteringconfig_storage_hive_storage_type == 'azure' and not meteringconfig_storage_azure_create_secret

- name: Configure Azure Storage
  block:
    - name: Validate Metering Azure bucket name
      assert:
        that:
          - meteringconfig_storage_azure_container_name != ""
          - meteringconfig_storage_azure_storage_account_name != ""
        msg: "storage.hive.azure.container and storage.hive.azure.storageAccountName cannot be empty"

    - name: Validate Metering Azure credentials
      assert:
        that:
          - meteringconfig_storage_azure_credentials_secret_name == ""
        msg: "storage.hive.azure.secretName is only used to reference existing secrets, must be empty if creating new secrets"

  when: meteringconfig_storage_hive_storage_type == 'azure' and meteringconfig_storage_azure_create_secret

