---

- name: Validate storage configuration
  assert:
    that:
      - meteringconfig_spec | json_query('storage.type') == "hive"
    msg: "Unsupported spec.storage.type, only 'hive' is  a supported option"

- name: Validate Hive storage configuration
  assert:
    that:
      - hiveStorageType is not undefined and hiveStorageType in ['s3', 'sharedPVC', 'hdfs', 'azure']
    msg: "Invalid spec.storage.hive.type: '{{ hiveStorageType }}', must be one of 's3', 'azure', or 'sharedPVC'"
  vars:
    hiveStorageType: "{{ meteringconfig_spec_overrides | json_query('storage.hive.type') }}"

- name: Configure TLS
  include_tasks: configure_tls.yml

- name: Configure Reporting
  include_tasks: configure_reporting.yml

- name: Configure Storage
  include_tasks: configure_storage.yml

- name: Store MeteringConfig spec into values file
  copy: content="{{ meteringconfig_spec }}" dest=/tmp/metering-values.yaml

- include_tasks: "{{ item }}"
  loop:
    - reconcile_metering.yml
    - reconcile_monitoring.yml
    - reconcile_hdfs.yml
    - reconcile_hive.yml
    - reconcile_presto.yml
    - reconcile_reporting_operator.yml
    - reconcile_reporting.yml
